### ISSUE TITLE
MVP and Stretch Goal Tracker

### ISSUE THREAD

**Issue by L0Lmaker** [CPSC319-2022/Yojana#123]
# Tasks
### Administrative Module:
- [X] Admins can add specific categories
- [X] Admins can select dates for specific categories
- [X] Categories are identified by specific icons as selected by the admins
- [X] Access to Admin privileges behind Active Directory
### End User Module:
- [X] Allows all users to view any of the dates created by Admins (read-only)
- [X] Creative UI
- [X] Allow users to filter which categories they want displayed
- [X] Multiple items per date, visually distinguishable
- [X] Ability to display the most up to date version of the calendar
- [x] Allow print functionality

## Non-functional requirements: (will update based on most up to date statistics)
- [X] Administrator access can have up to 5 concurrent users
- [X] End User access can have up to 100 concurrent users.

## Stretch Goals (in priority order)
- [X] Ability to view any changes in the master calendar 
- [x] (De-prioritized based on AE suggestion) Allow End Users to apply their own customized category and apply dates.  
  - This will overlap to the administrator categories/dates. 
  - These End user categories can also be included in a filtered view similar to the administrator’s categories. (use case described in sponsor doc)
- [x] Import function to highlight the certain dates such as this year’s month end dates. 
- [x] Allow ability to import any filter dates into an end users personal Outlook 365 calendar (AE’s standard)
- [X] Support both Edge and Chrome browsers (will be updated as time passes)
- [ ] Design UI to be AODA compliant 
- [ ] (De-prioritized based on AE suggestion)Allow an end user to share their calendar and personal categories to others in the organization (based on email address and/or AD credentials to accessing services)
